// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"database/sql"
)

type Customer struct {
	CustomerID    int32          `json:"customer_id"`
	Name          sql.NullString `json:"name"`
	Address       sql.NullString `json:"address"`
	ContactNumber sql.NullString `json:"contact_number"`
	Email         sql.NullString `json:"email"`
}

type Product struct {
	ProductID    int32          `json:"product_id"`
	Name         sql.NullString `json:"name"`
	Description  sql.NullString `json:"description"`
	Category     sql.NullString `json:"category"`
	SupplierID   sql.NullInt32  `json:"supplier_id"`
	Cost         sql.NullString `json:"cost"`
	SellingPrice sql.NullString `json:"selling_price"`
	Quantity     sql.NullInt32  `json:"quantity"`
}

type Sale struct {
	SaleID     int32          `json:"sale_id"`
	ProductID  sql.NullInt32  `json:"product_id"`
	CustomerID sql.NullInt32  `json:"customer_id"`
	Quantity   sql.NullInt32  `json:"quantity"`
	SaleDate   sql.NullTime   `json:"sale_date"`
	TotalPrice sql.NullString `json:"total_price"`
}

type Supplier struct {
	SupplierID    int32          `json:"supplier_id"`
	Name          sql.NullString `json:"name"`
	Address       sql.NullString `json:"address"`
	ContactNumber sql.NullString `json:"contact_number"`
	Email         sql.NullString `json:"email"`
}
