// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"context"
)

type Querier interface {
	CreateSupplier(ctx context.Context, arg CreateSupplierParams) (Supplier, error)
	DeleteSupplier(ctx context.Context, supplierID int32) error
	GetSupplier(ctx context.Context, supplierID int32) (Supplier, error)
	ListSupplier(ctx context.Context, arg ListSupplierParams) ([]Supplier, error)
	UpdateSupplier(ctx context.Context, arg UpdateSupplierParams) (Supplier, error)
}

var _ Querier = (*Queries)(nil)
